export const suggestedUsers = [
  {
    name: 'Jamie Bauch, PhD',
    title: 'Climate Scientist & Massachusetts',
    organization: 'Institute of Technology',
    profileImage: '/images/suggested-user.png',
    backgroundImage: '/images/suggested-card-bg.png',
    googleCount: 58,
    publicationsCount: 12,
    citationsCount: 89,
    patentsCount: 2,
    socialLinks: {
      github: 'https://github.com',
      website: 'https://jamiebauch.com',
      linkedin: 'https://linkedin.com/',
    },
  },
  {
    name: 'Dr. Emily Smith',
    title: 'AI Researcher & Data Scientist',
    organization: 'Stanford University',
    profileImage: '/images/suggested-user.png',
    backgroundImage: '/images/suggested-card-bg.png',
    googleCount: 72,
    publicationsCount: 20,
    citationsCount: 150,
    patentsCount: 5,
    socialLinks: {
      github: 'https://github.com',
      website: 'https://sparkixtech.com/',
      linkedin: 'https://linkedin.com/',
    },
  },
  {
    name: 'Michael Johnson',
    title: 'Blockchain Developer',
    organization: 'Ethereum Foundation',
    profileImage: '/images/suggested-user.png',
    backgroundImage: '/images/suggested-card-bg.png',
    googleCount: 34,
    publicationsCount: 8,
    citationsCount: 45,
    patentsCount: 1,
    socialLinks: {
      github: 'https://github.com',
      website: 'https://sparkixtech.com/',
      linkedin: 'https://linkedin.com/',
    },
  },
];
